---
# tasks file for postgres
- name: install postgres
  yum:
    name: postgresql-server
    state: latest
- name: enable postgres at boot
  service:
    name: postgresql
    enabled: yes
- name: initilize postgres
  shell: postgresql-setup initdb
  args:
    creates: /var/lib/pgsql/data/PG_VERSION
- name: start postgres
  service:
    name: postgresql.service
    state: started
